#!/usr/bin/env bash
# generate-docs.sh
#
# Generates auto-documentation for WannaBuild surfaces under docs/generated/.
# Outputs are deterministic (sorted ordering) and idempotent.
#
# Inputs:
#   - scripts/*.sh
#   - agents/*.md
#   - skills/*/SKILL.md, skills/*/*/SKILL.md
#   - skills/build/schemas/*.json
#
# Outputs:
#   - docs/generated/index.md
#   - docs/generated/scripts.md
#   - docs/generated/agents.md
#   - docs/generated/skills.md
#   - docs/generated/schemas.md
#
# Requirements: bash, awk, sed, sort, jq.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="${ROOT_DIR}/docs/generated"
GENERATED_BY="<!-- AUTO-GENERATED by scripts/generate-docs.sh — DO NOT EDIT MANUALLY."

if ! command -v jq >/dev/null 2>&1; then
  echo "error: jq is required but not installed" >&2
  exit 1
fi

mkdir -p "${OUT_DIR}"

# ---------- helpers ----------

# Read leading comment block from a shell script (lines starting with #, after
# optional shebang). Strips the leading '#' and one optional space.
extract_shell_header() {
  awk '
    NR == 1 && /^#!/ { next }
    /^#/ {
      sub(/^# ?/, "")
      print
      next
    }
    { exit }
  ' "$1"
}

# Extract function names defined in a shell script: matches both
#   funcname() { ... }
#   function funcname { ... }
extract_shell_functions() {
  awk '
    /^[[:space:]]*function[[:space:]]+[A-Za-z_][A-Za-z0-9_]*[[:space:]]*(\(\))?[[:space:]]*\{?/ {
      name = $2
      sub(/\(.*$/, "", name)
      print name
      next
    }
    /^[[:space:]]*[A-Za-z_][A-Za-z0-9_]*[[:space:]]*\(\)[[:space:]]*\{?/ {
      name = $1
      sub(/\(.*$/, "", name)
      print name
    }
  ' "$1" | sort -u
}

# Extract CLI flags from a shell script: looks for tokens like --flag or -f
# inside `case` blocks, getopts strings, and quoted patterns.
extract_shell_flags() {
  # Match -f / --flag / --flag=VAL inside the file; restrict to looks-like-CLI.
  grep -Eho -- '(^|[[:space:]"'"'"'\(\|])(--[A-Za-z][A-Za-z0-9._-]*|-[A-Za-z])' "$1" 2>/dev/null \
    | sed -E 's/^[[:space:]"'"'"'\(\|]*//' \
    | sort -u
}

# Extract YAML frontmatter value for a given key from a markdown file.
# Returns empty string if not found.
extract_frontmatter() {
  local file="$1"
  local key="$2"
  awk -v k="$key" '
    BEGIN { infm = 0; started = 0 }
    /^---[[:space:]]*$/ {
      if (!started) { started = 1; infm = 1; next }
      else { exit }
    }
    infm && $0 ~ "^"k"[[:space:]]*:" {
      sub("^"k"[[:space:]]*:[[:space:]]*", "")
      gsub(/^["\047]|["\047][[:space:]]*$/, "")
      print
      exit
    }
  ' "$file"
}

# Extract first non-empty paragraph after the first H1 heading. Used as a
# fallback description when frontmatter description is missing.
extract_first_paragraph() {
  awk '
    BEGIN { seen_h1 = 0; collecting = 0; buf = "" }
    /^# / { seen_h1 = 1; next }
    seen_h1 && /^[[:space:]]*$/ {
      if (collecting) { exit }
      next
    }
    seen_h1 && /^[^#]/ {
      collecting = 1
      if (buf == "") { buf = $0 } else { buf = buf " " $0 }
    }
    END { if (buf != "") print buf }
  ' "$1"
}

md_escape() {
  sed -e 's/|/\\|/g' -e 's/`/\\`/g'
}

# ---------- scripts.md ----------

generate_scripts_md() {
  local out="${OUT_DIR}/scripts.md"
  local sources
  sources="$(cd "${ROOT_DIR}" && ls scripts/*.sh 2>/dev/null | sort || true)"

  {
    printf '%s Source: scripts/*.sh -->\n\n' "${GENERATED_BY}"
    printf '# Scripts\n\n'
    printf 'Auto-documented inventory of every script under `scripts/`.\n\n'

    if [ -z "${sources}" ]; then
      printf '_No scripts found._\n'
      return 0
    fi

    while IFS= read -r relpath; do
      [ -z "${relpath}" ] && continue
      local filepath="${ROOT_DIR}/${relpath}"
      local name
      name="$(basename "${relpath}")"
      printf '## `%s`\n\n' "${name}"
      printf 'Path: `%s`\n\n' "${relpath}"

      local header
      header="$(extract_shell_header "${filepath}" || true)"
      if [ -n "${header}" ]; then
        printf '### Description\n\n'
        printf '```text\n%s\n```\n\n' "${header}"
      fi

      local functions
      functions="$(extract_shell_functions "${filepath}" || true)"
      if [ -n "${functions}" ]; then
        printf '### Functions\n\n'
        while IFS= read -r fn; do
          [ -z "${fn}" ] && continue
          printf -- '- `%s`\n' "${fn}"
        done <<< "${functions}"
        printf '\n'
      fi

      local flags
      flags="$(extract_shell_flags "${filepath}" || true)"
      if [ -n "${flags}" ]; then
        printf '### CLI flags / options observed\n\n'
        while IFS= read -r flag; do
          [ -z "${flag}" ] && continue
          printf -- '- `%s`\n' "${flag}"
        done <<< "${flags}"
        printf '\n'
      fi
    done <<< "${sources}"
  } > "${out}"
}

# ---------- agents.md ----------

generate_agents_md() {
  local out="${OUT_DIR}/agents.md"
  local sources
  sources="$(cd "${ROOT_DIR}" && ls agents/*.md 2>/dev/null | sort || true)"

  {
    printf '%s Source: agents/*.md -->\n\n' "${GENERATED_BY}"
    printf '# Agents\n\n'
    printf 'Specialist agent prompts, derived from YAML frontmatter and headings.\n\n'

    if [ -z "${sources}" ]; then
      printf '_No agents found._\n'
      return 0
    fi

    printf '| Name | Model | Description |\n'
    printf '|---|---|---|\n'

    while IFS= read -r relpath; do
      [ -z "${relpath}" ] && continue
      local filepath="${ROOT_DIR}/${relpath}"
      local name model desc
      name="$(extract_frontmatter "${filepath}" name)"
      [ -z "${name}" ] && name="$(basename "${relpath}" .md)"
      model="$(extract_frontmatter "${filepath}" model)"
      [ -z "${model}" ] && model="—"
      desc="$(extract_frontmatter "${filepath}" description)"
      if [ -z "${desc}" ]; then
        desc="$(extract_first_paragraph "${filepath}")"
      fi
      [ -z "${desc}" ] && desc="—"
      printf '| `%s` | %s | %s |\n' \
        "$(printf '%s' "${name}" | md_escape)" \
        "$(printf '%s' "${model}" | md_escape)" \
        "$(printf '%s' "${desc}" | md_escape)"
    done <<< "${sources}"
    printf '\n'
  } > "${out}"
}

# ---------- skills.md ----------

generate_skills_md() {
  local out="${OUT_DIR}/skills.md"
  local sources
  # Find every SKILL.md under skills/, sort deterministically.
  sources="$(cd "${ROOT_DIR}" && find skills -type f -name 'SKILL.md' 2>/dev/null | LC_ALL=C sort || true)"

  {
    printf '%s Source: skills/**/SKILL.md -->\n\n' "${GENERATED_BY}"
    printf '# Skills\n\n'
    printf 'Workflow and phase contracts available to the orchestrator.\n\n'

    if [ -z "${sources}" ]; then
      printf '_No skills found._\n'
      return 0
    fi

    printf '| Skill | Path | Description |\n'
    printf '|---|---|---|\n'

    while IFS= read -r relpath; do
      [ -z "${relpath}" ] && continue
      local filepath="${ROOT_DIR}/${relpath}"
      local skill_name desc
      skill_name="$(extract_frontmatter "${filepath}" name)"
      if [ -z "${skill_name}" ]; then
        skill_name="$(dirname "${relpath}" | awk -F/ '{print $NF}')"
      fi
      desc="$(extract_frontmatter "${filepath}" description)"
      if [ -z "${desc}" ]; then
        desc="$(extract_first_paragraph "${filepath}")"
      fi
      [ -z "${desc}" ] && desc="—"
      printf '| `%s` | `%s` | %s |\n' \
        "$(printf '%s' "${skill_name}" | md_escape)" \
        "$(printf '%s' "${relpath}" | md_escape)" \
        "$(printf '%s' "${desc}" | md_escape)"
    done <<< "${sources}"
    printf '\n'
  } > "${out}"
}

# ---------- schemas.md ----------

generate_schemas_md() {
  local out="${OUT_DIR}/schemas.md"
  local sources
  sources="$(cd "${ROOT_DIR}" && ls skills/build/schemas/*.json 2>/dev/null | sort || true)"

  {
    printf '%s Source: skills/build/schemas/*.json -->\n\n' "${GENERATED_BY}"
    printf '# Schemas\n\n'
    printf 'JSON schemas consumed by `scripts/validate-wannabuild-artifacts.sh`.\n\n'

    if [ -z "${sources}" ]; then
      printf '_No schemas found._\n'
      return 0
    fi

    while IFS= read -r relpath; do
      [ -z "${relpath}" ] && continue
      local filepath="${ROOT_DIR}/${relpath}"
      local title required props_block

      title="$(jq -r '.title // empty' "${filepath}" 2>/dev/null || true)"
      [ -z "${title}" ] && title="$(basename "${relpath}" .schema.json)"

      printf '## `%s`\n\n' "${title}"
      printf 'Path: `%s`\n\n' "${relpath}"

      required="$(jq -r '.required // [] | sort | .[]' "${filepath}" 2>/dev/null | LC_ALL=C sort -u || true)"
      if [ -n "${required}" ]; then
        printf '### Required fields\n\n'
        while IFS= read -r f; do
          [ -z "${f}" ] && continue
          printf -- '- `%s`\n' "${f}"
        done <<< "${required}"
        printf '\n'
      fi

      props_block="$(jq -r '
        (.properties // {}) as $p
        | ($p | keys_unsorted | sort) as $ks
        | $ks[]
        | . as $k
        | $p[$k] as $v
        | [
            $k,
            ($v.type // "—" | if type == "array" then join(" \\| ") else . end),
            ($v.description // "—" | gsub("\n"; " ") | gsub("\\|"; "\\|"))
          ]
        | "| `\(.[0])` | \(.[1]) | \(.[2]) |"
      ' "${filepath}" 2>/dev/null || true)"

      if [ -n "${props_block}" ]; then
        printf '### Properties\n\n'
        printf '| Field | Type | Description |\n'
        printf '|---|---|---|\n'
        printf '%s\n\n' "${props_block}"
      fi
    done <<< "${sources}"
  } > "${out}"
}

# ---------- index.md ----------

generate_index_md() {
  local out="${OUT_DIR}/index.md"
  {
    printf '%s Source: docs/generated/* -->\n\n' "${GENERATED_BY}"
    printf '# Generated Documentation\n\n'
    printf 'Auto-generated indexes of WannaBuild surfaces. Regenerate with:\n\n'
    printf '```bash\n'
    printf 'bash scripts/generate-docs.sh\n'
    printf '```\n\n'
    printf '## Contents\n\n'
    printf -- '- [Scripts](scripts.md) — every `scripts/*.sh` with description, functions, and flags\n'
    printf -- '- [Agents](agents.md) — specialist agent prompts (`agents/*.md`)\n'
    printf -- '- [Skills](skills.md) — workflow contracts (`skills/**/SKILL.md`)\n'
    printf -- '- [Schemas](schemas.md) — JSON schemas (`skills/build/schemas/*.json`)\n'
  } > "${out}"
}

main() {
  generate_scripts_md
  generate_agents_md
  generate_skills_md
  generate_schemas_md
  generate_index_md
  echo "Generated docs in ${OUT_DIR}"
}

main "$@"
